"""Initial tables

Revision ID: ee38a850524a
Revises:
Create Date: 2026-05-30 11:50:54.830363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee38a850524a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name'),
    schema='gac'
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='gac'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['gac.users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    schema='gac'
    )
    op.create_index(op.f('ix_gac_orders_client_id'), 'orders', ['client_id'], unique=False, schema='gac')
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['gac.roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gac.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='gac'
    )
    op.create_table('order_items',
    sa.Column('item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('product_key', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['gac.orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    schema='gac'
    )
    op.create_index(op.f('ix_gac_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='gac')
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transaction_ref', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['gac.orders.order_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    schema='gac'
    )
    op.create_index(op.f('ix_gac_payments_client_id'), 'payments', ['client_id'], unique=False, schema='gac')
    op.create_index(op.f('ix_gac_payments_order_id'), 'payments', ['order_id'], unique=False, schema='gac')
    op.create_table('shipments',
    sa.Column('shipment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('shipping_carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['gac.orders.order_id'], ),
    sa.PrimaryKeyConstraint('shipment_id'),
    schema='gac'
    )
    op.create_index(op.f('ix_gac_shipments_order_id'), 'shipments', ['order_id'], unique=False, schema='gac')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gac_shipments_order_id'), table_name='shipments', schema='gac')
    op.drop_table('shipments', schema='gac')
    op.drop_index(op.f('ix_gac_payments_order_id'), table_name='payments', schema='gac')
    op.drop_index(op.f('ix_gac_payments_client_id'), table_name='payments', schema='gac')
    op.drop_table('payments', schema='gac')
    op.drop_index(op.f('ix_gac_order_items_order_id'), table_name='order_items', schema='gac')
    op.drop_table('order_items', schema='gac')
    op.drop_table('user_roles', schema='gac')
    op.drop_index(op.f('ix_gac_orders_client_id'), table_name='orders', schema='gac')
    op.drop_table('orders', schema='gac')
    op.drop_table('users', schema='gac')
    op.drop_table('roles', schema='gac')
    # ### end Alembic commands ###
