"""Initial tables

Revision ID: ee38a850524a
Revises:
Create Date: 2026-05-30 11:50:54.830363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee38a850524a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Reconciliación con una base que se adelantó a alembic.
#
# Esta migración se autogeneró el 2026-06-09 declarando las siete tablas, pero
# nunca llegó a aplicarse: el despliegue no corría migraciones y `alembic
# upgrade head` solo existía como paso manual del README. Mientras tanto la
# base se había creado con `scripts/create_tables.py` cuando el proyecto solo
# tenía autenticación, así que hoy tiene roles, users y user_roles, y le faltan
# orders, order_items, payments y shipments.
#
# Envolver las llamadas en guardas de existencia permite ejecutarla sobre esa
# base: crea lo que falta y salta lo que ya está. Las definiciones de las tablas
# NO se han tocado — son exactamente las del commit original.
# ---------------------------------------------------------------------------


def _inspector():
    return sa.inspect(op.get_bind())


def _has_table(name: str) -> bool:
    return _inspector().has_table(name, schema='gac')


def _create_table(name, *args, **kwargs):
    if _has_table(name):
        return
    op.create_table(name, *args, **kwargs)


def _create_index(index_name, table_name, *args, **kwargs):
    if not _has_table(table_name):
        return
    existing = {ix['name'] for ix in _inspector().get_indexes(table_name, schema='gac')}
    if index_name in existing:
        return
    op.create_index(index_name, table_name, *args, **kwargs)


def _drop_table(name, **kwargs):
    if _has_table(name):
        op.drop_table(name, **kwargs)


def _drop_index(index_name, table_name, **kwargs):
    if not _has_table(table_name):
        return
    existing = {ix['name'] for ix in _inspector().get_indexes(table_name, schema='gac')}
    if index_name in existing:
        op.drop_index(index_name, table_name=table_name, **kwargs)


def upgrade() -> None:
    """Upgrade schema. Idempotente: ver la nota de reconciliación arriba."""
    # El esquema puede no existir en una base recién creada.
    op.execute('CREATE SCHEMA IF NOT EXISTS gac')
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table('roles',
    sa.Column('role_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name'),
    schema='gac'
    )
    _create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='gac'
    )
    _create_table('orders',
    sa.Column('order_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['gac.users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    schema='gac'
    )
    _create_index(op.f('ix_gac_orders_client_id'), 'orders', ['client_id'], unique=False, schema='gac')
    _create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['gac.roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['gac.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='gac'
    )
    _create_table('order_items',
    sa.Column('item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('product_key', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['gac.orders.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    schema='gac'
    )
    _create_index(op.f('ix_gac_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='gac')
    _create_table('payments',
    sa.Column('payment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transaction_ref', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['gac.orders.order_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    schema='gac'
    )
    _create_index(op.f('ix_gac_payments_client_id'), 'payments', ['client_id'], unique=False, schema='gac')
    _create_index(op.f('ix_gac_payments_order_id'), 'payments', ['order_id'], unique=False, schema='gac')
    _create_table('shipments',
    sa.Column('shipment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('shipping_carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['gac.orders.order_id'], ),
    sa.PrimaryKeyConstraint('shipment_id'),
    schema='gac'
    )
    _create_index(op.f('ix_gac_shipments_order_id'), 'shipments', ['order_id'], unique=False, schema='gac')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_index(op.f('ix_gac_shipments_order_id'), 'shipments', schema='gac')
    _drop_table('shipments', schema='gac')
    _drop_index(op.f('ix_gac_payments_order_id'), 'payments', schema='gac')
    _drop_index(op.f('ix_gac_payments_client_id'), 'payments', schema='gac')
    _drop_table('payments', schema='gac')
    _drop_index(op.f('ix_gac_order_items_order_id'), 'order_items', schema='gac')
    _drop_table('order_items', schema='gac')
    _drop_table('user_roles', schema='gac')
    _drop_index(op.f('ix_gac_orders_client_id'), 'orders', schema='gac')
    _drop_table('orders', schema='gac')
    _drop_table('users', schema='gac')
    _drop_table('roles', schema='gac')
    # ### end Alembic commands ###
